// export const CHECK_LOGIN_TRY = "CHECK_LOGIN_TRY";
// export const RESET_LOGIN_STATE = "RESET_LOGIN_STATE1";
export const VALIDATE_TOKEN_REQUEST = "VALIDATE_TOKEN_REQUEST";
export const VALIDATE_TOKEN_FAILURE = "VALIDATE_TOKEN_FAILURE";
export const VALIDATE_TOKEN_SUCCESS = "VALIDATE_TOKEN_SUCCESS";

export const SET_LOGIN_TYPE = "SET_LOGIN_TYPE";

export const STORAGE_TYPE_COOKIE = "STORAGE_TYPE_COOKIE";
export const STORAGE_TYPE_LOCAL_STORAGE = "STORAGE_TYPE_LOCAL_STORAGE";

export const LOGIN_REQUEST_BASIC = "LOGIN_REQUEST_BASIC";
export const LOGIN_SUCCESS_BASIC = "LOGIN_SUCCESS_BASIC";
export const LOGIN_FAILURE_BASIC = "LOGIN_FAILURE_BASIC";
export const LOGOUT_REQUEST_BASIC = "LOGOUT_REQUEST_BASIC";
export const LOGOUT_SUCCESS_BASIC = "LOGOUT_SUCCESS_BASIC";
export const LOGOUT_FAILURE_BASIC = "LOGOUT_FAILURE_BASIC";

export const LOGIN_REQUEST_TOKEN = "LOGIN_REQUEST_TOKEN";
export const LOGIN_SUCCESS_TOKEN = "LOGIN_SUCCESS_TOKEN";
export const LOGIN_FAILURE_TOKEN = "LOGIN_FAILURE_TOKEN";
export const LOGOUT_REQUEST_TOKEN = "LOGOUT_REQUEST_TOKEN";
export const LOGOUT_SUCCESS_TOKEN = "LOGOUT_SUCCESS_TOKEN";
export const LOGOUT_FAILURE_TOKEN = "LOGOUT_FAILURE_TOKEN";

export const LOGIN_SUCCESS_SESSION = "LOGIN_SUCCESS_SESSION";
export const LOGIN_FAILURE_SESSION = "LOGIN_FAILURE_SESSION";
export const LOGOUT_REQUEST_SESSION = "LOGOUT_REQUEST_SESSION";
export const LOGOUT_SUCCESS_SESSION = "LOGOUT_SUCCESS_SESSION";
export const LOGOUT_FAILURE_SESSION = "LOGOUT_FAILURE_SESSION";

export const USER_DETAIL = "USER_DETAIL";
